# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Technical Publications
  fr: Publications techniques
email: mcafeetechpubs@gmail.com
description:
  en: Hello!
  fr: Bonjour
index:
  en:
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mcafeetechpubs.github.io" # the base hostname & protocol for your site
twitter_username: pmasalsk
github_username:  mcafeetechpubs

# Build settings
markdown: kramdown
